package com.lawencon.glexy.email;

import javax.activation.DataSource;
import javax.mail.internet.MimeMessage;
import javax.mail.util.ByteArrayDataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Component;

import com.lawencon.glexy.helper.EmailHelper;

@Component
//@Profile("email")
public class EmailHandler {
	
	@Autowired
	protected JavaMailSender mailSender;
	
	@Async
	public void sendSimpleMessage(String to, String subject, String header, EmailHelper data) throws Exception{


		MimeMessage message = mailSender.createMimeMessage();
	     
	    MimeMessageHelper helper = new MimeMessageHelper(message, true);
	   
	    helper.setFrom("noreply@baeldung.com");
	    helper.setTo(to);
	    helper.setSubject(subject);
	    helper.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
	    		+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
	    		+ "<head>\r\n"
	    		+ "\r\n"
	    		+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
	    		+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
	    		+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
	    		+ "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"><!--<![endif]-->\r\n"
	    		+ "  <title></title>\r\n"
	    		+ "  \r\n"
	    		+ "    <style type=\"text/css\">\r\n"
	    		+ "      table, td { color: #000000; } @media only screen and (min-width: 620px) {\r\n"
	    		+ "  .u-row {\r\n"
	    		+ "    width: 600px !important;\r\n"
	    		+ "  }\r\n"
	    		+ "  .u-row .u-col {\r\n"
	    		+ "    vertical-align: top;\r\n"
	    		+ "  }\r\n"
	    		+ "\r\n"
	    		+ "  .u-row .u-col-100 {\r\n"
	    		+ "    width: 600px !important;\r\n"
	    		+ "  }\r\n"
	    		+ "\r\n"
	    		+ "}\r\n"
	    		+ "\r\n"
	    		+ "@media (max-width: 620px) {\r\n"
	    		+ "  .u-row-container {\r\n"
	    		+ "    max-width: 100% !important;\r\n"
	    		+ "    padding-left: 0px !important;\r\n"
	    		+ "    padding-right: 0px !important;\r\n"
	    		+ "  }\r\n"
	    		+ "  .u-row .u-col {\r\n"
	    		+ "    min-width: 320px !important;\r\n"
	    		+ "    max-width: 100% !important;\r\n"
	    		+ "    display: block !important;\r\n"
	    		+ "  }\r\n"
	    		+ "  .u-row {\r\n"
	    		+ "    width: calc(100% - 40px) !important;\r\n"
	    		+ "  }\r\n"
	    		+ "  .u-col {\r\n"
	    		+ "    width: 100% !important;\r\n"
	    		+ "  }\r\n"
	    		+ "  .u-col > div {\r\n"
	    		+ "    margin: 0 auto;\r\n"
	    		+ "  }\r\n"
	    		+ "}\r\n"
	    		+ "body {\r\n"
	    		+ "  margin: 0;\r\n"
	    		+ "  padding: 0;\r\n"
	    		+ "}\r\n"
	    		+ "\r\n"
	    		+ "table,\r\n"
	    		+ "tr,\r\n"
	    		+ "td {\r\n"
	    		+ "  vertical-align: top;\r\n"
	    		+ "  border-collapse: collapse;\r\n"
	    		+ "}\r\n"
	    		+ "\r\n"
	    		+ "p {\r\n"
	    		+ "  margin: 0;\r\n"
	    		+ "}\r\n"
	    		+ "\r\n"
	    		+ ".ie-container table,\r\n"
	    		+ ".mso-container table {\r\n"
	    		+ "  table-layout: fixed;\r\n"
	    		+ "}\r\n"
	    		+ "\r\n"
	    		+ "* {\r\n"
	    		+ "  line-height: inherit;\r\n"
	    		+ "}\r\n"
	    		+ "\r\n"
	    		+ "a[x-apple-data-detectors='true'] {\r\n"
	    		+ "  color: inherit !important;\r\n"
	    		+ "  text-decoration: none !important;\r\n"
	    		+ "}\r\n"
	    		+ "\r\n"
	    		+ "</style>\r\n"
	    		+ "  \r\n"
	    		+ "  \r\n"
	    		+ "\r\n"
	    		+ "<link href=\"https://fonts.googleapis.com/css?family=Lato:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\">\r\n"
	    		+ "\r\n"
	    		+ "</head>\r\n"
	    		+ "\r\n"
	    		+ "<body class=\"clean-body u_body\" style=\"margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #ffffff;color: #000000\">\r\n"
	    		+ "\r\n"
	    		+ "  <table style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;min-width: 320px;Margin: 0 auto;background-color: #ffffff;width:100%\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
	    		+ "  <tbody>\r\n"
	    		+ "  <tr style=\"vertical-align: top\">\r\n"
	    		+ "    <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top\">\r\n"
	    		+ "   \r\n"
	    		+ "    \r\n"
	    		+ "\r\n"
	    		+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
	    		+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #235784;\">\r\n"
	    		+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
	    		+ "     \r\n"
	    		+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
	    		+ "  <div style=\"width: 100% !important;\">\r\n"
	    		+ " <div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
	    		+ "  \r\n"
	    		+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
	    		+ "  <tbody>\r\n"
	    		+ "    <tr>\r\n"
	    		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:25px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
	    		+ "        \r\n"
	    		+ "<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\r\n"
	    		+ "  <tr>\r\n"
	    		+ "    <td style=\"padding-right: 0px;padding-left: 0px;\" align=\"left\">\r\n"
	    		+ "      \r\n"
	    		+ "      <img align=\"left\" border=\"0\" src=\"https://s3.amazonaws.com/unroll-images-production/projects%2F0%2F1641461549851-LogoText.png\" alt=\"Image\" title=\"Image\" style=\"outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;clear: both;display: inline-block !important;border: none;height: auto;float: none;width: 45%;max-width: 261px;\" width=\"261\"/>\r\n"
	    		+ "      \r\n"
	    		+ "    </td>\r\n"
	    		+ "  </tr>\r\n"
	    		+ "</table>\r\n"
	    		+ "\r\n"
	    		+ "      </td>\r\n"
	    		+ "    </tr>\r\n"
	    		+ "  </tbody>\r\n"
	    		+ "</table>\r\n"
	    		+ "\r\n"
	    		+ " </div>\r\n"
	    		+ "  </div>\r\n"
	    		+ "</div>\r\n"
	    		+ "\r\n"
	    		+ "    </div>\r\n"
	    		+ "  </div>\r\n"
	    		+ "</div>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
	    		+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f2f0eb;\">\r\n"
	    		+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
	    		+ "  \r\n"
	    		+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
	    		+ "  <div style=\"width: 100% !important;\">\r\n"
	    		+ "  <div style=\"padding: 100px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
	    		+ "  \r\n"
	    		+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
	    		+ "  <tbody>\r\n"
	    		+ "    <tr>\r\n"
	    		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:21px 10px 0px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
	    		+ "        \r\n"
	    		+ "  <div style=\"color: #010101; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
	    		+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 50px; line-height: 100.8px;\">Password</span></p>\r\n"
	    		+ "  </div>\r\n"
	    		+ "\r\n"
	    		+ "      </td>\r\n"
	    		+ "    </tr>\r\n"
	    		+ "  </tbody>\r\n"
	    		+ "</table>\r\n"
	    		+ "\r\n"
	    		+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
	    		+ "  <tbody>\r\n"
	    		+ "    <tr>\r\n"
	    		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
	    		+ "        \r\n"
	    		+ "  <div style=\"line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
	    		+ "    <p style=\"font-size: 14px; line-height: 140%;\"><span style=\"font-size: 30px; line-height: 25.2px;\"><b>"+data.getValueName()+"</b></span></p>\r\n"
	    		+ "  </div>\r\n"
	    		+ "\r\n"
	    		+ "      </td>\r\n"
	    		+ "    </tr>\r\n"
	    		+ "  </tbody>\r\n"
	    		+ "</table>\r\n"
	    		+ "\r\n"
	    		+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
	    		+ "  <tbody>\r\n"
	    		+ "    <tr>\r\n"
	    		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
	    		+ "        \r\n"
	    		+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"84%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #BBBBBB;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
	    		+ "    <tbody>\r\n"
	    		+ "      <tr style=\"vertical-align: top\">\r\n"
	    		+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
	    		+ "          <span>&#160;</span>\r\n"
	    		+ "        </td>\r\n"
	    		+ "      </tr>\r\n"
	    		+ "    </tbody>\r\n"
	    		+ "  </table>\r\n"
	    		+ "\r\n"
	    		+ "      </td>\r\n"
	    		+ "    </tr>\r\n"
	    		+ "  </tbody>\r\n"
	    		+ "</table>\r\n"
	    		+ "\r\n"
	    		+ "  </div>\r\n"
	    		+ "  </div>\r\n"
	    		+ "</div>\r\n"
	    		+ "\r\n"
	    		+ "    </div>\r\n"
	    		+ "  </div>\r\n"
	    		+ "</div>\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "\r\n"
	    		+ "<div class=\"u-row-container\" style=\"padding: 0px;background-color: transparent\">\r\n"
	    		+ "  <div class=\"u-row\" style=\"Margin: 0 auto;min-width: 320px;max-width: 600px;overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;background-color: #f2f0eb;\">\r\n"
	    		+ "    <div style=\"border-collapse: collapse;display: table;width: 100%;background-color: transparent;\">\r\n"
	    		+ "    \r\n"
	    		+ "<div class=\"u-col u-col-100\" style=\"max-width: 320px;min-width: 600px;display: table-cell;vertical-align: top;\">\r\n"
	    		+ "  <div style=\"width: 100% !important;\">\r\n"
	    		+ "  <div style=\"padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\"><!--<![endif]-->\r\n"
	    		+ "  \r\n"
	    		+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
	    		+ "  <tbody>\r\n"
	    		+ "    <tr>\r\n"
	    		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px 40px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
	    		+ "        \r\n"
	    		+ "  <div style=\"color: #666666; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
	    		+ "    <p style=\"font-size: 14px; line-height: 140%;\">&nbsp;</p>\r\n"
	    		+ "<p style=\"font-size: 14px; line-height: 140%;\">&nbsp;</p>\r\n"
	    		+ "<p style=\"font-size: 14px; line-height: 140%;\">&nbsp;</p>\r\n"
	    		+ "  </div>\r\n"
	    		+ "\r\n"
	    		+ "      </td>\r\n"
	    		+ "    </tr>\r\n"
	    		+ "  </tbody>\r\n"
	    		+ "</table>\r\n"
	    		+ "\r\n"
	    		+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
	    		+ "  <tbody>\r\n"
	    		+ "    <tr>\r\n"
	    		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:0px 40px 10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
	    		+ "        \r\n"
	    		+ "  <div style=\"color: #414b41; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
	    		+ "    <p style=\"line-height: 140%; font-size: 14px;\"><span style=\"font-size: 12px; line-height: 16.8px;\"><strong>&nbsp;</strong></span></p>\r\n"
	    		+ "  </div>\r\n"
	    		+ "\r\n"
	    		+ "      </td>\r\n"
	    		+ "    </tr>\r\n"
	    		+ "  </tbody>\r\n"
	    		+ "</table>\r\n"
	    		+ "\r\n"
	    		+ "<table style=\"font-family:'Lato',sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\">\r\n"
	    		+ "  <tbody>\r\n"
	    		+ "    <tr>\r\n"
	    		+ "      <td style=\"overflow-wrap:break-word;word-break:break-word;padding:10px;font-family:'Lato',sans-serif;\" align=\"left\">\r\n"
	    		+ "        \r\n"
	    		+ "  <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse;table-layout: fixed;border-spacing: 0;mso-table-lspace: 0pt;mso-table-rspace: 0pt;vertical-align: top;border-top: 1px solid #f8f8f8;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
	    		+ "    <tbody>\r\n"
	    		+ "      <tr style=\"vertical-align: top\">\r\n"
	    		+ "        <td style=\"word-break: break-word;border-collapse: collapse !important;vertical-align: top;font-size: 0px;line-height: 0px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%\">\r\n"
	    		+ "          <span>&#160;</span>\r\n"
	    		+ "        </td>\r\n"
	    		+ "      </tr>\r\n"
	    		+ "    </tbody>\r\n"
	    		+ "  </table>\r\n"
	    		+ "\r\n"
	    		+ "      </td>\r\n"
	    		+ "    </tr>\r\n"
	    		+ "  </tbody>\r\n"
	    		+ "</table>\r\n"
	    		+ "\r\n"
	    		+ " </div>\r\n"
	    		+ "  </div>\r\n"
	    		+ "</div>\r\n"
	    		+ "\r\n"
	    		+ "    </div>\r\n"
	    		+ "  </div>\r\n"
	    		+ "</div> \r\n"
	    		+ "    </td>\r\n"
	    		+ "  </tr>\r\n"
	    		+ "  </tbody>\r\n"
	    		+ "  </table>\r\n"
	    		+ "\r\n"
	    		+ "</body>\r\n"
	    		+ "\r\n"
	    		+ "</html>\r\n"
	    		+ "",true);
	    mailSender.send(message);
	}
	
	@Async
	public void sendExpiredMessage(String to, String subject, String header ,EmailHelper data) throws Exception{

		
		MimeMessage message = mailSender.createMimeMessage();
	     
	    MimeMessageHelper helper = new MimeMessageHelper(message, true);
	   
	    helper.setFrom("noreply@baeldung.com");
	    helper.setTo(to);
	    helper.setSubject(subject);
	    helper.setText("<!DOCTYPE html>"
	    		+ "<html>"
	    		+ "<head>"
	    		+ "    <style>"
	    		+ "        .body {\r\n"
	    		+ "            background-color: #235784;"
	    		+ "            width: 60vw;"
	    		+ "            height: 60vh;"
	    		+ "			   border-radius: 10px;"
	    		+ "            display: inline-block;"
	    		+ "            margin-left:  20px;"
	    		+ "        }"
	    		+ "        .body__email {"
	    		+ "            background-color: white;"
	    		+ "            width: 60%;"
	    		+ "            height: 60%;"
	    		+ "            display: inline-block;"
	    		+ "			   border: 5px #FFCA03 solid;"
	    		+ "			   border-radius: 10px;"
	    		+ "            margin-left:  20%;"
	    		+ "            margin-top:  10%;"
	    		+ "        }"
	    		+ "        .body__email h1 {"
	    		+ "            margin-top: 5%;"
	    		+ "          text-align: center;"
	    		+ "        }"
	    		+ "        .body__email h2 {"
	    		+ "          text-align: center;"
	    		+ "        }"
	    		+ "    </style>"
	    		+ "</head>"
	    		+ "<body>"
	    		+ "    <div class=\"body\">"
	    		+ "        <div class=\"body__email\">"
	    		+ "            <h1>"+header+"</h1>"
	    		+ "            <h2>"+data.getEmployeeName()+"</h2>"
	    		+ "            <h2>"+data.getValueName()+"</h2>"
	    		+ "            <h2>"+data.getExpiredDate() +"</h2>"
	    		+ "        </div>"
	    		+ "    </div>"
	    		+ "</body>"
	    		+ "</html>",true);
	    
	    mailSender.send(message);
	}
	
	@Async
	public void sendReport(String to, String subject, String header ,EmailHelper data) throws Exception{

		MimeMessage message = mailSender.createMimeMessage();
	     
	    MimeMessageHelper helper = new MimeMessageHelper(message, true);
	   
	    helper.setFrom("noreply@baeldung.com");
	    helper.setTo(to);
	    helper.setSubject(subject);
	    helper.setText("Report " + data.getFileName(),true);
	    
	    DataSource dataSource = new ByteArrayDataSource(data.getAttach(), "application/pdf");
	    helper.addAttachment(data.getFileName(), dataSource);
	    
	    mailSender.send(message);
	}


}
